from .alias_registry import AliasRegistry
from .utils import normalize_whitespace, strip_parenthetical_suffix, to_proper_case


class PlayerAliasRegistry(AliasRegistry):
    """Common IPL player aliases. Extensible via register()."""

    def __init__(self) -> None:
        super().__init__()
        self._register_known_players()

    def _register_known_players(self) -> None:
        self.register("MS Dhoni", "Dhoni", "MSD", "Mahendra Singh Dhoni", "M Dhoni")
        self.register("Virat Kohli", "Kohli", "V Kohli", "Virat")
        self.register("Rohit Sharma", "Sharma", "R Sharma", "Rohit")
        self.register("Jasprit Bumrah", "Bumrah", "J Bumrah")
        self.register("KL Rahul", "Rahul", "K L Rahul", "K Rahul")
        self.register("Rishabh Pant", "Pant", "R Pant")
        self.register("Shubman Gill", "Gill", "S Gill")
        self.register("Hardik Pandya", "Hardik", "H Pandya", "Pandya")
        self.register("Ravindra Jadeja", "Jadeja", "R Jadeja", "Sir Jadeja")
        self.register("Suryakumar Yadav", "Suryakumar", "SK Yadav", "S Yadav")
        self.register("Ravichandran Ashwin", "Ashwin", "R Ashwin")
        self.register("Mohammed Shami", "Shami", "M Shami")
        self.register("Shikhar Dhawan", "Dhawan", "S Dhawan")
        self.register("Kuldeep Yadav", "Kuldeep", "K Yadav")
        self.register("Yuzvendra Chahal", "Chahal", "Y Chahal")
        self.register("Pat Cummins", "Cummins", "P Cummins")
        self.register("David Warner", "Warner", "D Warner")
        self.register("Jos Buttler", "Buttler", "J Buttler")
        self.register("Glenn Maxwell", "Maxwell", "G Maxwell", "Maxi")
        self.register("Andre Russell", "Russell", "A Russell", "Dre Russell")
        self.register("Sunil Narine", "Narine", "S Narine")
        self.register("Rashid Khan", "Rashid", "R Khan")
        self.register("Sam Curran", "S Curran")
        self.register("Ben Stokes", "Stokes", "B Stokes")
        self.register("Jofra Archer", "Archer", "J Archer")
        self.register("Kagiso Rabada", "Rabada", "K Rabada")
        self.register("Trent Boult", "Boult", "T Boult")
        self.register("Faf du Plessis", "Faf", "du Plessis")
        self.register("Sanju Samson", "Samson", "S Samson")
        self.register("Shreyas Iyer", "Iyer", "S Iyer")
        self.register("Ishan Kishan", "Kishan", "I Kishan")
        self.register("Dinesh Karthik", "Karthik", "D Karthik", "DK")
        self.register("Devon Conway", "Conway", "D Conway")
        self.register("Mitchell Marsh", "M Marsh")
        self.register("Cameron Green", "C Green")
        self.register("Tim David", "T David")
        self.register("Moeen Ali", "M Ali")
        self.register("Shivam Dube", "Dube", "S Dube")
        self.register("Rajat Patidar", "Patidar", "R Patidar")
        self.register("Nitish Rana", "N Rana")
        self.register("Prithvi Shaw", "P Shaw")
        self.register("Mukesh Kumar", "Mukesh")
        self.register("Deepak Chahar", "Chahar", "D Chahar")
        self.register("Umesh Yadav", "U Yadav")
        self.register("Prasidh Krishna", "Krishna", "P Krishna")
        self.register("Arshdeep Singh", "Arshdeep", "A Singh")
        self.register("Khaleel Ahmed", "Khaleel")
        self.register("T Natarajan", "Natarajan")
        self.register("Umran Malik", "Umran")
        self.register("Rinku Singh", "Rinku")
        self.register("Tilak Varma", "Tilak")
        self.register("Abdul Samad", "Samad")
        self.register("Shahbaz Ahmed", "Shahbaz")
        self.register("Washington Sundar", "Washington", "W Sundar")
        self.register("B Sai Sudharsan", "Sai Sudharsan", "Sudharsan")
        self.register("Yashasvi Jaiswal", "Jaiswal", "Y Jaiswal")
        self.register("Riyan Parag", "Parag", "R Parag")
        self.register("Dhruv Jurel", "Jurel", "D Jurel")
        self.register("Harshal Patel", "H Patel", "Harshal")
        self.register("Mohammad Nabi", "Nabi")
        self.register("Kieron Pollard", "Pollard", "K Pollard")
        self.register("Imran Tahir", "Tahir")
        self.register("Keshav Maharaj", "Maharaj", "K Maharaj")
        self.register("Ruchit Ahir", "Ahir", "R Ahir", "Ruchir Ahir")
        self.register("Madushanka", "Dushmantha Madushanka")
        self.register("Nuwan Thushara", "Thushara", "N Thushara", "Thusara")
        # CSK
        self.register("Ruturaj Gaikwad", "Gaikwad", "R Gaikwad")
        self.register("Tushar Deshpande", "Deshpande", "T Deshpande")
        self.register("Matheesha Pathirana", "Pathirana", "M Pathirana")
        self.register("Maheesh Theekshana", "Theekshana", "M Theekshana")
        self.register("Shardul Thakur", "S Thakur", "Lord Thakur")
        self.register("Ajinkya Rahane", "Rahane", "A Rahane")
        self.register("Mitchell Santner", "Santner", "M Santner")
        self.register("Shaik Rasheed", "Rasheed")
        self.register("Mustafizur Rahman", "Mustafizur", "Fizz", "M Rahman")
        self.register("Rajvardhan Hangargekar", "Hangargekar")
        self.register("Prashant Solanki", "Solanki")
        self.register("Simarjeet Singh", "Simarjeet")
        self.register("Nishant Sindhu", "Sindhu")
        self.register("Sameer Rizvi", "Rizvi")
        self.register("Aravelly Avanish", "Avanish")
        self.register("Ayush Mhatre", "Mhatre", "A Mhatre")
        self.register("Ramakrishna Ghosh", "Ghosh", "R Ghosh")
        self.register("Dian Forrester", "Dian", "Forrester", "D Forrester")
        self.register("Macneil Noronha", "Noronha", "M Noronha")
        self.register("Kuldip Yadav", "Kuldip")
        # MI
        self.register("Romario Shepherd", "Shepherd", "R Shepherd")
        self.register("Piyush Chawla", "P Chawla")
        self.register("Kumar Kartikeya", "Kartikeya")
        self.register("Akash Madhwal", "Madhwal", "A Madhwal")
        self.register("Arjun Tendulkar", "A Tendulkar")
        self.register("Dewald Brevis", "Brevis", "Baby AB")
        self.register("Naman Dhir", "Dhir")
        self.register("Gerald Coetzee", "Coetzee", "G Coetzee")
        self.register("Jason Behrendorff", "Behrendorff", "J Behrendorff")
        self.register("Nuwan Thushara", "Thushara", "N Thushara")
        self.register("Shreyas Gopal", "S Gopal")
        # RCB
        self.register("Mohammed Siraj", "Siraj", "M Siraj")
        self.register("Josh Hazlewood", "Hazlewood", "J Hazlewood")
        self.register("Kyle Jamieson", "Jamieson", "K Jamieson")
        self.register("Anuj Rawat", "A Rawat")
        self.register("Akash Deep", "A Deep")
        self.register("Mahipal Lomror", "Lomror", "M Lomror")
        self.register("Suyash Prabhudessai", "Prabhudessai")
        self.register("Will Jacks", "Jacks", "W Jacks")
        self.register("Reece Topley", "Topley", "R Topley")
        self.register("Tom Curran", "T Curran")
        self.register("Manoj Bhandage", "Bhandage")
        self.register("Saurav Chauhan", "Chauhan")
        self.register("Vijaykumar Vyshak", "Vyshak", "V Vyshak")
        self.register("Swapnil Singh", "Swapnil")
        self.register("Yash Dayal", "Dayal", "Y Dayal")
        self.register("Wanindu Hasaranga", "Hasaranga", "W Hasaranga")
        # KKR
        self.register("Varun Chakravarthy", "Varun", "V Chakravarthy", "Chakravarthy")
        self.register("Ramandeep Singh", "Ramandeep")
        self.register("Venkatesh Iyer", "V Iyer")
        self.register("Phil Salt", "Salt", "P Salt")
        self.register("Jason Roy", "Roy", "J Roy")
        self.register("Mitchell Starc", "Starc", "M Starc")
        self.register("Rahmanullah Gurbaz", "Gurbaz", "R Gurbaz")
        self.register("Vaibhav Arora", "V Arora")
        self.register("Harshit Rana", "H Rana")
        self.register("Suyash Sharma", "Suyash")
        self.register("Chetan Sakariya", "Sakariya", "C Sakariya")
        self.register("KS Bharat", "Bharat", "K Bharat")
        self.register("Angkrish Raghuvanshi", "Raghuvanshi")
        self.register("Mujeeb Ur Rahman", "Mujeeb")
        self.register("Gus Atkinson", "Atkinson", "G Atkinson")
        self.register("Luvnith Sisodia", "Sisodia", "L Sisodia")
        self.register("Saurabh Dubey", "Dubey", "S Dubey")
        # SRH
        self.register("Kane Williamson", "Kane", "K Williamson")
        self.register("Jhye Richardson", "Richardson", "J Richardson")
        self.register("Bhuvneshwar Kumar", "Bhuvneshwar", "B Kumar", "Bhuvi")
        self.register("Aiden Markram", "Markram", "A Markram")
        self.register("Heinrich Klaasen", "Klaasen", "H Klaasen")
        self.register("Travis Head", "Head", "T Head")
        self.register("Abhishek Sharma", "Abhishek")
        self.register("Mayank Agarwal", "M Agarwal")
        self.register("Rahul Tripathi", "Tripathi", "R Tripathi")
        self.register("Glenn Phillips", "Phillips", "G Phillips")
        self.register("Marco Jansen", "Jansen", "M Jansen")
        self.register("Fazalhaq Farooqi", "Farooqi", "F Farooqi")
        self.register("Nithish Reddy", "Reddy", "N Reddy")
        self.register("Mayank Markande", "Markande", "M Markande")
        self.register("Jaydev Unadkat", "Unadkat", "J Unadkat")
        self.register("Shivam Mavi", "Mavi", "S Mavi")
        self.register("David Payne", "Payne", "D Payne")
        self.register("RS Ambrish", "Ambrish")
        # RR
        self.register("Shimron Hetmyer", "Hetmyer", "S Hetmyer")
        self.register("Sandeep Sharma", "Sandeep")
        self.register("Kuldeep Sen", "K Sen")
        self.register("Navdeep Saini", "Saini", "N Saini")
        self.register("Obed McCoy", "McCoy", "O McCoy")
        self.register("Donovan Ferreira", "Ferreira")
        self.register("Adam Zampa", "Zampa", "A Zampa")
        self.register("Avesh Khan", "A Khan")
        # NOTE: Bare "Dubey" alias is owned by Saurabh Dubey (KKR) above. Shubham
        # Dubey (RR) shares the surname; the DB resolver disambiguates by team.
        self.register("Shubham Dubey")
        self.register("Nandre Burger", "Burger", "N Burger")
        self.register("Tom Kohler-Cadmore", "Kohler-Cadmore")
        self.register("Rovman Powell", "Powell", "R Powell")
        self.register("Emanjot Chahal", "Emanjot")
        # DC
        self.register("Axar Patel", "Axar", "A Patel")
        self.register("Anrich Nortje", "Nortje", "A Nortje")
        self.register("Lungi Ngidi", "Ngidi", "L Ngidi")
        self.register("Marcus Stoinis", "Stoinis", "M Stoinis")
        self.register("Alex Carey", "Carey", "A Carey")
        self.register("Amit Mishra", "A Mishra")
        self.register("Ishant Sharma", "I Sharma")
        self.register("Lalit Yadav", "L Yadav")
        self.register("Yash Dhull", "Dhull")
        self.register("Rasikh Salam", "Salam")
        self.register("Shai Hope", "Hope", "S Hope")
        self.register("Harry Brook", "Brook", "H Brook")
        self.register("Jake Fraser-McGurk", "Fraser-McGurk", "Jake McGurk")
        self.register("Tristan Stubbs", "Stubbs", "T Stubbs")
        # LSG
        self.register("Ravi Bishnoi", "Bishnoi", "R Bishnoi")
        self.register("Deepak Hooda", "Hooda", "D Hooda")
        self.register("Krunal Pandya", "K Pandya")
        self.register("Mark Wood", "Wood", "M Wood")
        self.register("Nicholas Pooran", "Pooran", "N Pooran", "Pooran")
        self.register("Quinton de Kock", "de Kock", "Q de Kock", "Quinton")
        self.register("Ayush Badoni", "Badoni")
        self.register("Mohsin Khan", "M Khan")
        self.register("Yash Thakur", "Y Thakur")
        self.register("K Gowtham", "Gowtham", "Krishnappa Gowtham")
        self.register("Ashton Turner", "Turner", "A Turner")
        self.register("David Willey", "Willey", "D Willey")
        self.register("Shamar Joseph", "S Joseph")
        self.register("Mayank Yadav", "M Yadav")
        self.register("Naveen-ul-Haq", "Naveen")
        self.register("Devdutt Padikkal", "Padikkal", "D Padikkal")
        # PBKS
        self.register("Jonny Bairstow", "Bairstow", "J Bairstow")
        self.register("Liam Livingstone", "Livingstone", "L Livingstone")
        self.register("Rahul Chahar", "R Chahar")
        self.register("Jitesh Sharma", "Jitesh")
        self.register("Prabhsimran Singh", "Prabhsimran")
        self.register("Shahrukh Khan", "S Khan")
        self.register("Harpreet Brar", "Brar", "H Brar")
        self.register("Nathan Ellis", "Ellis", "N Ellis")
        self.register("Sikandar Raza", "Raza", "S Raza")
        self.register("Chris Woakes", "Woakes", "C Woakes")
        self.register("Rilee Rossouw", "Rossouw", "R Rossouw")
        self.register("Ashutosh Sharma", "Ashutosh")
        self.register("Vidwath Kaverappa", "Kaverappa")
        self.register("Shashank Singh", "Shashank")
        self.register("Atharva Taide", "Taide")
        # GT
        self.register("David Miller", "Miller", "D Miller")
        self.register("Wriddhiman Saha", "Saha", "W Saha")
        self.register("Vijay Shankar", "V Shankar")
        self.register("Rahul Tewatia", "Tewatia", "R Tewatia")
        self.register("Noor Ahmad", "Noor")
        self.register("Joshua Little", "Little", "J Little")
        self.register("Mohit Sharma", "M Sharma")
        self.register("Darshan Nalkande", "Nalkande")
        self.register("Siddharth Kaul", "S Kaul")
        self.register("Sai Kishore", "S Kishore")
        self.register("Jayant Yadav", "J Yadav")
        self.register("Spencer Johnson", "S Johnson")
        self.register("Azmatullah Omarzai", "Omarzai")
        self.register("Robin Minz", "Minz")
        self.register("Connor Esterhuizen", "Esterhuizen", "C Esterhuizen")
        self.register("Jacob Bethell", "Bethell")
        self.register("Tom Banton", "Banton")


class PlayerNameNormalizer:
    def __init__(self, alias_registry: PlayerAliasRegistry | None = None) -> None:
        self._registry = alias_registry or PlayerAliasRegistry()

    def normalize(self, name: str) -> str:
        name = strip_parenthetical_suffix(name)

        # Priority 5: Deterministic Noise Stripping
        noise_phrases = [
            "Cricinfo",
            "Cricbuzz",
            "India Today",
            "Rediff",
            "Google News",
            "Business Standard",
            "The News Mill",
            "TV Bharat",
            "Injury Crisis Deepens",
            "Returns",
            "Still Unavailable",
        ]
        # Remove noise phrases case-insensitively
        import re

        for phrase in noise_phrases:
            pattern = re.compile(re.escape(phrase), re.IGNORECASE)
            name = pattern.sub("", name)

        # Clean up any leftover leading/trailing non-alphanumeric chars (like colons)
        name = re.sub(r"^[^a-zA-Z0-9]+|[^a-zA-Z0-9]+$", "", name)

        name = normalize_whitespace(name)
        resolved = self._registry.resolve(name)
        if resolved is not None:
            return resolved
        return to_proper_case(name)
