from ..domain.enums import EventType

EVENT_KEYWORDS: dict[EventType, list[str]] = {
    EventType.RULED_OUT: [
        "ruled out",
        "ruled out of",
        "out of the tournament",
        "out of the season",
        "out of ipl",
        "withdrawn",
        "withdraws",
        "pulls out",
        "pulled out",
        "unavailable",
        "doubtful",
        "forced to withdraw",
        "will miss",
        "set to miss",
        "out for the season",
        "side-lined",
        "setback",
    ],
    EventType.REPLACEMENT_SIGNED: [
        "replacement",
        "replaces",
        "signed as replacement",
        "named as replacement",
        "replacement player",
        "replacement signing",
        "brought in for",
        "drafted in for",
        "roped in",
        "called in as cover",
        "emergency signing",
        "replacement for",
        "signs as replacement",
        "named replacement",
    ],
    EventType.SUSPENSION: [
        "suspended",
        "suspension",
        "banned",
        "handed a ban",
        "match ban",
        "sanction",
        "penalty",
        "code of conduct breach",
    ],
    EventType.RECOVERY: [
        "recovered",
        "recovery",
        "fit again",
        "regained fitness",
        "returning from injury",
        "back from injury",
        "returns from injury",
        "back in training",
        "resumes training",
        "in contention",
        "nears return",
        "close to return",
    ],
    EventType.AVAILABLE_AGAIN: [
        "available again",
        "declared fit",
        "cleared to play",
        "given green light",
        "available for selection",
        "returns to squad",
        "back in the squad",
        "ruled available",
        "fit to play",
        "passed fit",
        "back to full fitness",
        "all clear",
        "passed medical",
        "ready to play",
        "rejoins squad",
    ],
    EventType.INJURY: [
        "injury",
        "injured",
        "suffers",
        "strain",
        "tear",
        "fracture",
        "side strain",
        "sidelined",
        "nursing",
        "carried off",
        "subbed out",
        "hurt",
        "niggle",
        "complaint",
        "discomfort",
        "scan",
        "surgery",
        "operation",
        "rehab",
        "injury scare",
        "injury blow",
        "breaks down",
        "limps off",
    ],
    EventType.ILLNESS: [
        "illness",
        "fever",
        "sick",
        "unwell",
        "virus",
        "food poisoning",
        "stomach bug",
        "viral",
        "infection",
    ],
    EventType.NATIONAL_DUTY: [
        "national duty",
        "international duty",
        "called up",
        "national team call",
        "country duty",
        "national call-up",
        "selected for",
        "international break",
    ],
    EventType.RESTED: [
        "rested",
        "given a rest",
        "rest period",
        "rested from",
        "rotation",
        "managed workload",
    ],
    EventType.PERSONAL_LEAVE: [
        "personal leave",
        "personal reasons",
        "family reasons",
        "bereavement",
        "family emergency",
        "personal matter",
        "bereavement leave",
        "away from the team",
    ],
}

PUBLISHER_NAMES: set[str] = {
    "cricinfo",
    "espn cricinfo",
    "google news",
    "yahoo sports",
    "india today",
    "sportstar",
    "rediff",
    "the times",
    "the times of india",
    "hindustan times",
    "times of india",
    "indian express",
    "the hindu",
    "news18",
    "ndtv sports",
    "sportskeeda",
    "cricbuzz",
    "icc cricket",
    "firstpost",
    "outlook india",
    "the indian express",
    "espn",
    "ndtv",
    "sports news",
    "cricket news",
    "times now",
    "india tv",
    "abp news",
    "zee news",
    "aaj tak",
    "open magazine",
    "cricket country",
    "tv sports",
    "tv bharat",
    "business standard",
    "the news mill",
    "etv bharat",
    "herald goa",
    "bhaskar",
    "deccan herald",
    "the hindu",
    "deccan chronicle",
    "free press journal",
    "mid-day",
    "mumbai mirror",
    "anandabazar patrika",
    "india today online",
    "india today hindi",
    "news9",
    "republic world",
    "the quint",
    "the print",
    "scroll.in",
    "the wire",
    "first cricket",
    "cricfit",
    "cricketnmore",
    "sportswallah",
    "sportstiger",
    "loksatta",
    "lokmat",
    "sakal",
    "maharashtra times",
    "gujarat samachar",
    "divya bhaskar",
    "sandesh",
    "anandabazar",
    "ei samay",
    "aaj tak hindi",
    "aaj tak english",
    "abp live",
    "zee hindi",
    "zee news english",
}

# Headline fragments / articles / connector words that should NEVER
# appear inside a player name. Used to detect and reject contamination.
HEADLINE_FRAGMENTS: set[str] = {
    "the",
    "a",
    "an",
    "his",
    "her",
    "their",
    "in",
    "on",
    "at",
    "to",
    "of",
    "as",
    "by",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "from",
    "with",
    "for",
    "and",
    "or",
    "but",
    "not",
    "big",
    "small",
    "top",
    "new",
    "old",
    "first",
    "last",
    "next",
    "former",
    "current",
    "ex",
    "incoming",
    "outgoing",
    "star",
    "young",
    "veteran",
    "senior",
    "junior",
    "meet",
    "super",
    # Pronouns (coreference leakage)
    "he",
    "she",
    "it",
    "they",
    "we",
    "you",
    # Role descriptors
    "captain",
    # Verbs/adverbs from headline leakage
    "still",
    "deepens",
    "played",
    # Month names — never valid player names
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december",
    # Month abbreviations
    "jan",
    "feb",
    "mar",
    "apr",
    "jun",
    "jul",
    "aug",
    "sep",
    "oct",
    "nov",
    "dec",
}

# Event keywords that should never appear in a player name. These are
# the "as replacement", "rope in" type fragments that bleed into the
# extracted candidate.
EVENT_FRAGMENTS: set[str] = {
    "ruled out",
    "ruled out of",
    "out of the tournament",
    "out of the season",
    "out of ipl",
    "withdrawn",
    "withdraws",
    "pulls out",
    "pulled out",
    "unavailable",
    "doubtful",
    "set to miss",
    "side-lined",
    "setback",
    "replacement",
    "replacement player",
    "replacement signing",
    "replaces",
    "replacement for",
    "signed as replacement",
    "named as replacement",
    "named replacement",
    "signs as replacement",
    "roped in",
    "rope in",
    "brought in for",
    "drafted in for",
    "called in as cover",
    "emergency signing",
    "signs",
    "signed",
    "sign",
    "returns",
    "returning",
    "return",
    "returns from injury",
    "back from injury",
    "back in training",
    "resumes training",
    "in contention",
    "nears return",
    "close to return",
    "available again",
    "declared fit",
    "cleared to play",
    "given green light",
    "available for selection",
    "returns to squad",
    "back in the squad",
    "ruled available",
    "fit to play",
    "passed fit",
    "back to full fitness",
    "all clear",
    "passed medical",
    "ready to play",
    "rejoins squad",
    "injury",
    "injured",
    "suffers",
    "strain",
    "tear",
    "fracture",
    "sidelined",
    "nursing",
    "carried off",
    "subbed out",
    "hurt",
    "niggle",
    "complaint",
    "discomfort",
    "scan",
    "surgery",
    "operation",
    "rehab",
    "injury scare",
    "injury blow",
    "breaks down",
    "limps off",
    "illness",
    "fever",
    "sick",
    "unwell",
    "virus",
    "food poisoning",
    "stomach bug",
    "viral",
    "infection",
    "national duty",
    "international duty",
    "called up",
    "national team call",
    "country duty",
    "national call-up",
    "selected for",
    "international break",
    "rested",
    "given a rest",
    "rest period",
    "rested from",
    "rotation",
    "managed workload",
    "personal leave",
    "personal reasons",
    "family reasons",
    "bereavement",
    "family emergency",
    "personal matter",
    "bereavement leave",
    "away from the team",
    "suspended",
    "suspension",
    "banned",
    "handed a ban",
    "match ban",
    "sanction",
    "penalty",
    "code of conduct breach",
    "as injury",
    "as injury replacement",
    "as replacement",
    "as a replacement",
    "as cover",
    "as cover for",
    "for the remainder",
    "for the rest",
    "for the season",
    "in for",
    "bring in",
    "bring",
    "rope",
    "in to replace",
    "to replace",
    "set to",
    "due to",
    "because of",
    "out of",
    "loses",
    "lose",
    "lost",
    "missing",
    "misses",
    "miss",
    "missed",
    "rule out",
    "rules out",
    "meet",
    "meets",
    "skip",
    "skips",
    "skipped",
    "skipped the",
    "faces",
    "face",
    "faced",
    "rule",
    "rules",
    "pick",
    "picks",
    "picked",
    "picks up",
    "picked up",
    "sign akash",
    "sk sign",
    "sk signs",
    "sk named",
    "lends",
    "rosters",
    "named",
    "name",
    "name as",
    "named as",
    "ruled-out",
    "recover",
    "recovers",
    "recovered",
    "regained",
    "ready",
    "absorb",
    "absorbed",
    "new zealand",
    "in pakistan super",
    "former",
    "former rajasthan royals",
    "former mumbai indians",
    "former csk",
    "former rcb",
    "former kkr",
    "former srh",
    "former rr",
    "former dc",
    "former lsg",
    "former pbks",
    "former gt",
}

# Indian states / regions / nationalities that frequently leak into
# headlines ("South African all-rounder", "Karnataka's Macneil Noronha").
REGION_NAMES: set[str] = {
    "south african",
    "karnataka",
    "keralite",
    "kerala",
    "tamil nadu",
    "tamil",
    "andhra",
    "telangana",
    "mumbai",
    "delhi",
    "rajasthan",
    "kolkata",
    "chennai",
    "bengaluru",
    "bangalore",
    "hyderabad",
    "punjabi",
    "punjab",
    "gujarati",
    "gujarat",
    "sindhi",
    "marathi",
    "bengali",
    "bengal",
    "srilankan",
    "sri lankan",
    "australian",
    "english",
    "irish",
    "scottish",
    "welsh",
    "kiwi",
    "caribbean",
    "zimbabwean",
    "afghan",
    "afghani",
    "nepali",
    "bangladeshi",
    "pakistani",
    "indian",
    "south african",
    "west indian",
    "new zealander",
    "indian origin",
    "us-born",
    "uk-born",
}

# Headline boilerplate phrases that are NEVER player names.
HEADLINE_BOILERPLATE: set[str] = {
    "injured players list",
    "injury crisis",
    "injury update",
    "injury blow",
    "injury scare",
    "injury concern",
    "injury list",
    "injury news",
    "injury report",
    "injury status",
    "injury latest",
    "full list",
    "latest update",
    "latest news",
    "ruled out of",
    "replacement for",
    "replacement player",
    "replacement signing",
    "injury replacement",
    "ruled out",
    "in pakistan super",
    "in to",
    "in for",
    "the times",
    "in bbl",
    "in cpl",
    "in psl",
    "in psl 2026",
    "in ipl 2026",
    "for ipl 2026",
    "for the season",
    "for the rest of",
    "for the remainder of",
    "for the remainder",
    "meet",
    "former rajasthan royals",
    "former mumbai indians",
    "former chennai super kings",
    "former royal challengers",
    "former kolkata knight riders",
    "former sunrisers hyderabad",
    "former delhi capitals",
    "former lucknow super giants",
    "former punjab kings",
    "former gujarat titans",
    "a former rajasthan royals",
    "a former mumbai indians",
    "a former chennai super kings",
    "a former royal challengers",
    "a former kolkata knight riders",
    "a former sunrisers hyderabad",
    "a former delhi capitals",
    "a former lucknow super giants",
    "a former punjab kings",
    "a former gujarat titans",
}

GENERIC_NOUNS: set[str] = {
    "latest",
    "this",
    "full",
    "news",
    "update",
    "report",
    "analysis",
    "preview",
    "review",
    "summary",
    "recap",
    "highlights",
    "coverage",
    "feature",
    "story",
    "article",
    "blog",
    "edition",
    "breaking",
    "top",
    "trending",
    "popular",
    "today",
    "watch",
    "photos",
    "gallery",
    "videos",
    "schedule",
    "points table",
    "live",
    "excellence",
    "player",
    "league",
    "centre",
}

COUNTRY_NAMES: set[str] = {
    "india",
    "australia",
    "england",
    "south africa",
    "new zealand",
    "west indies",
    "sri lanka",
    "bangladesh",
    "afghanistan",
    "pakistan",
    "zimbabwe",
    "ireland",
    "scotland",
    "netherlands",
    "nepal",
}

EVENT_PRIORITY: list[EventType] = [
    EventType.RULED_OUT,
    EventType.REPLACEMENT_SIGNED,
    EventType.SUSPENSION,
    EventType.RECOVERY,
    EventType.AVAILABLE_AGAIN,
    EventType.INJURY,
    EventType.ILLNESS,
    EventType.NATIONAL_DUTY,
    EventType.RESTED,
    EventType.PERSONAL_LEAVE,
]

TEAM_NAMES: dict[str, list[str]] = {
    "Chennai Super Kings": ["csk", "chennai super kings", "super kings", "chennai"],
    "Mumbai Indians": ["mi", "mumbai indians", "mumbai"],
    "Royal Challengers Bengaluru": [
        "rcb",
        "royal challen",
        "bengaluru",
        "bangalore",
    ],
    "Kolkata Knight Riders": ["kkr", "kolkata knight riders", "kolkata", "knight riders"],
    "Sunrisers Hyderabad": ["srh", "sunrisers hyderabad", "hyderabad", "sunrisers"],
    "Rajasthan Royals": ["rr", "rajasthan royals", "rajasthan"],
    "Delhi Capitals": ["dc", "delhi capitals", "delhi"],
    "Lucknow Super Giants": ["lsg", "lucknow super giants", "lucknow", "super giants"],
    "Punjab Kings": ["pbks", "punjab kings", "punjab"],
    "Gujarat Titans": ["gt", "gujarat titans", "gujarat"],
}

INJURY_KEYWORDS: dict[str, list[str]] = {
    "knee": ["knee", "knee injury", "knee strain", "knee issue"],
    "hamstring": ["hamstring", "hamstring strain", "hamstring tear"],
    "back": ["back", "back injury", "back problem", "back spasm"],
    "groin": ["groin", "groin strain", "groin injury"],
    "ankle": ["ankle", "ankle injury", "ankle sprain", "ankle twist"],
    "shoulder": ["shoulder", "shoulder injury", "dislocated shoulder"],
    "calf": ["calf", "calf strain", "calf injury"],
    "quadriceps": ["quad", "quadriceps", "quad strain"],
    "side": ["side strain", "intercostal"],
    "hamstring tear": ["hamstring tear", "torn hamstring"],
    "finger": ["finger", "finger injury", "broken finger"],
    "concussion": ["concussion", "head injury"],
    "elbow": ["elbow", "elbow injury"],
}

HIGH_CONFIDENCE_PHRASES: list[str] = [
    "ruled out",
    "confirmed",
    "announced",
    "official",
    "declared",
    "signed",
    "banned",
    "released",
    "suspended",
    "suspension",
]

MEDIUM_CONFIDENCE_PHRASES: list[str] = [
    "expected",
    "expected to",
    "likely",
    "likely to",
    "reportedly",
    "understood to",
    "set to miss",
]

LOW_CONFIDENCE_PHRASES: list[str] = [
    "speculation",
    "rumored",
    "rumoured",
    "unclear",
    "may miss",
    "could be",
    "possible",
    "potentially",
    "might",
    "uncertain",
]
